basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.Task:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        description: 任務名稱
        type: string
      status:
        description: 0 = 未完成，1 = 已完成
        type: integer
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple RESTful API for managing tasks.
  title: Task API
  version: "1.0"
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: Create a task with name and status
      parameters:
      - description: Task to create
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create a new task
      tags:
      - tasks
swagger: "2.0"
